apiVersion: v1
kind: Service
metadata:
  labels:
    app: new-site
  name: new-site
  namespace: leadfy-pub
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: new-site
