#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative 'context'
app_conf = DeployContext.new.get

cmd = ARGV[0] || 'apply'

unless %w[delete apply].include?(cmd)
  warn('cmd must be delete or apply')
  exit(1)
end

%w[
  config
  secrets
  net
  app
].each do |dir|
  system("kubectl #{cmd} -f #{app_conf[:dir_deploy]}/#{dir}")
end
